### ISSUE TITLE
Fancy Settings

### ISSUE THREAD

**Issue by RichardLitt** [OpenKnowledgeButton/OpenKnowledgeButton#3]
Using fancy settings is a UI decision, which will percolate up the chain to each project using OKB. Using it isn't uncontroversial; for Beagle, we want all of the user settings to be in our own extension, not in the Chrome Extensions folder, for instance. 

What do you think? Is this absolutely necessary to the product?

**Comment by mitar** [comment]
You can always decide that for your sub-extension you do not want to use browser's settings interface, but on the other hand, if you want to use browser's settings for your sub-extension, this is one of those things which are browser depended and would have to be supported by the top-level extension.

**Comment by RichardLitt** [comment]
Cool. Will be coming back to this when we move away from Chrome (aka, have some of our main features down and figure we should go cross-browser).
